# ghc 7.10.3
resolver: lts-6.35

# ghc 8.0.1
# PROB: packman won't compile
# resolver: lts-7.10

# Local packages, usually specified by relative directory name
packages:
- '.'

flags:
   serialise:
     newtime15: true

extra-deps:
- packman-0.3.0
- binary-0.8.5.1
- cereal-0.5.4.0
- flat-0.3
- store-0.4.3.1
- store-core-0.4.1
- serialise-0.1.0.0
- cborg-0.1.1.0
- th-utilities-0.2.0.1
- datasets-0.2.1
- criterion-1.1.4.0
- code-page-0.1.1
- optparse-applicative-0.13.0.0
- mono-traversable-1.0.2
