# ghc 7.10.3
resolver: lts-6.26

# ghc 8.0.1
# PROB: packman won't compile
# resolver: lts-7.10


# Local packages, usually specified by relative directory name
packages:
- '.'

- location:
   git: https://github.com/well-typed/binary-serialise-cbor
   commit: 1e11ea5cc7810d241b2fe1bca0ed435baa4d4371
  extra-dep: true

flags:
  binary-serialise-cbor:
    newtime15: true

extra-deps:
- packman-0.3.0
- binary-0.8.4.1
